database:
  pg_url: postgres://postgres:123456@172.18.32.1:3308/e_tech_assist # postgresql连接地址
  redis_url: redis://:123456@172.18.32.1:3310 # redis连接地址

jwt:
  secret: secret # jwt密钥
  exp: 4363200 # 30*24*60*60 30天

server:
  ip: "[::]" # 监听地址
  port: 3000 # 监听端口

api:
  prefix: api # api前缀
  version: v1 # api版本

captcha:
  length: 4 # 验证码长度
  width: 150 # 验证码宽度
  height: 50 # 验证码高度
  dark_mode: false # 深色模式
  complexity: 3 # 复杂度
  compression: 30 # 压缩率
  exp: 600 # 过期时间

wxapp:
  appid: wxd9a698e4a2ce155a # 小程序appid
  secret: b5d2277361b537680f7617a7f625c4ae # 小程序secret
  api_domain: https://api.weixin.qq.com # 微信api地址
  wechat_open_uri: https://open.weixin.qq.com/connect/qrconnect # 微信开放平台地址
  default_user_agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36 # 默认user-agent

email:
  email_addr: 17633877664@163.com # 邮箱地址
  code: PRBASIOXUARJZSZA # 授权码
  smtp_addr: smtp.163.com # smtp邮箱服务器地址

mime:
  image: 
    size: 10485760 # 1024 * 1024 * 10 / 10MB
    types:
      - image/gif
      - image/png
      - image/jpeg
      - image/bmp
      - image/webp
  application:
    size: 104857600 # 1024 * 1024 * 100 / 100MB
    types:
      - application/zip
      - application/x-rar-compressed
      - application/x-7z-compressed
      - application/x-tar
      - application/x-gzip
      - application/x-bzip2
      - application/x-bzip